kind: Deployment
apiVersion: apps/v1
metadata:
  name:  firstdeploy
  labels:
    app: Node1
spec:
  template:
    metadata:
     name: podefirst1
     labels:
        app: Node
    spec:
      containers:
        - name: podefirst2
          image: princyvarunp/test
  replicas: 4
  selector:
    matchLabels:
     app: Node
 
 